### ISSUE TITLE
[Suggetion]

### ISSUE THREAD

**Issue by dadevguy** [supercrafter333/PlayedTime#1]
## Add ScoreHUD Support

* Please Add ScoreHUD Score So We Can Do Like  

```
Time Played: {played.time}
```

**Comment by supercrafter333** [comment]
Already planned but thx for your suggestion :)

**Comment by supercrafter333** [comment]
Done!
[GitHub](https://github.com/supercrafter333/ScoreHudX/tree/main/PlayedTimeScore)
[Poggit](https://poggit.pmmp.io/ci/supercrafter333/ScoreHudX/PlayedTimeScore)

**Comment by dadevguy** [comment]
:)
