### ISSUE TITLE
Feature 

### ISSUE THREAD

**Issue by kingboydeve** [supercrafter333/PlayedTime#14]
Add
Per week , month , season or customed time leader board and score hud and dayli players time loging

**Comment by kingboydeve** [comment]
Fpr pm4

**Comment by kingboydeve** [comment]
No pm5

**Comment by supercrafter333** [comment]
PlayedTime won't get new features and updates for PM4. The PM4-version of PlayedTime (and also theSpawn) are end-of-life.
Please use PM5.

**Comment by kingboydeve** [comment]
Are you see my first message? :|
