### ISSUE TITLE
Bug time count

### ISSUE THREAD

**Issue by Nat392** [supercrafter333/PlayedTime#15]
Hello,

We discovered a bug on the PM5 version of the plugin that was not present before: we use PlayedTime for a reward system. Under PM4, we didn't have to disconnect and then reconnect for the plugin to get the player's game time, but now we do.

**Comment by Nat392** [comment]
Any news ?

**Comment by supercrafter333** [comment]
I currently don't have time that much. I'll try to test it next week.
Sorry 🙏

**Comment by supercrafter333** [comment]
## Unable to reproduce bug

Hello,
I tried to reproduce your bug but I wasn't able to reproduce.
Please send me your reward-plugin (maybe per [discord dm](https://chrx-toph.tk/discordapp.com/users/511252471616897024)) and give some more information how to reproduce the bug.

> This issue will be closed (as done) until the bug can be reproduced.

best regards
supercrafter333

**Comment by Nat392** [comment]
I sent it to you a while ago, and you said you'd seen the problem (my account : horharoon) @supercrafter333

**Comment by supercrafter333** [comment]
I tested your plugin and I also can't confirm this issue.
