### ISSUE TITLE
error

### ISSUE THREAD

**Issue by OfficialOst** [supercrafter333/PlayedTime#17]
I use the translator to write to you.

How can I show the play time from this plugin in Scorehud?

**Comment by supercrafter333** [comment]
You can download the Scorehud-addon here: [Poggit](https://poggit.pmmp.io/ci/supercrafter333/ScoreHudX/PlayedTimeScore)

The tags that can be used for Scorehud can be found here: [GitHub](https://github.com/supercrafter333/ScoreHudX/blob/main/PlayedTimeScore/README.md)

If you have any other questions or problems, please feel free to contact me or write a comment in this issue.

**Comment by OfficialOst** [comment]
Thank you for your help!

пн, 19 авг. 2024 г., 01:27 Christoph R. ***@***.***>:
