### ISSUE TITLE
Vorschlag

### ISSUE THREAD

**Issue by GamilinoMC** [supercrafter333/PlayedTime#3]
Es wäre nice wenn man das Plugin mit einer Datenpank verbinden kann um die Spielzeit serverübergreifend zu machen

**Comment by supercrafter333** [comment]
Da Poggit nur Datenbank-Plugins mit Asynchron Support annimmt, werde ich wenn erstmal eine Configurations-Datei machen, bei der man einstellen kann, wo die Zeit abgespeichert werden soll.

**Comment by supercrafter333** [comment]
#4
