### ISSUE TITLE
Add settings to change the letters displayed in ScoreHud

### ISSUE THREAD

**Issue by MrBlasyMSK** [supercrafter333/PlayedTime#5]
As mentioned in supercrafter333's Discord, it would be very useful to add a setting which lets you change the letters you want to appear in the scorehud so that anyone can change it in their own way

https://discord.com/channels/847099444465238036/847102241994833961/974317838699474975

[I am opening this issue so that you can close it and let poggit know that it has been added and in case someone needs to see it].

**Comment by supercrafter333** [comment]
For TO-DO.

**Comment by supercrafter333** [comment]
Done in [6750d23](https://github.com/supercrafter333/ScoreHudX/commit/6750d230b0dbd92c628295d0ec6254f83f13f865).
