### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by Tuvalu23** [supercrafter333/PlayedTime#8]
#0 plugins/PlayedTime_dev-9.phar/src/PlayedTimeManager(189): DateInterval->__construct(string[1] P)
  #1 plugins/PlayedTime_dev-9.phar/src/PlayedTimeManager(216): supercrafter333\PlayedTime\PlayedTimeManager->getTimeFromConfig(object ipad54\netherblocks\player\Player#394171)
  #2 plugins/PlayedTime_dev-9.phar/src/PlayedTimeManager(119): supercrafter333\PlayedTime\PlayedTimeManager->calculateTotalTime(object ipad54\netherblocks\player\Player#394171)
  #3 plugins/PlayedTimeScore_dev-6.phar/src/listeners/EventListener(50): supercrafter333\PlayedTime\PlayedTimeManager->getTotalTime(object ipad54\netherblocks\player\Player#394171)
  #4 plugins/PlayedTimeScore_dev-6.phar/src/ScorehudUpdateTask(14): supercrafter333\PlayedTimeScore\listeners\EventListener->sendUpdate(object ipad54\netherblocks\player\Player#394171)
  #5 pmsrc/src/scheduler/TaskHandler(117): supercrafter333\PlayedTimeScore\ScorehudUpdateTask->onRun()
  #6 pmsrc/src/scheduler/TaskScheduler(144): pocketmine\scheduler\TaskHandler->run()
  #7 pmsrc/src/plugin/PluginManager(478): pocketmine\scheduler\TaskScheduler->mainThreadHeartbeat(integer 901)
  #8 pmsrc/src/Server(1769): pocketmine\plugin\PluginManager->tickSchedulers(integer 901)
  #9 pmsrc/src/Server(1658): pocketmine\Server->tick()
  #10 pmsrc/src/Server(1047): pocketmine\Server->tickProcessor()
  #11 pmsrc/src/PocketMine(304): pocketmine\Server->__construct(object BaseClassLoader#2, object pocketmine\utils\MainLogger#3, string[16] /home/container/, string[24] /home/container/plugins/)
  #12 pmsrc/src/PocketMine(327): pocketmine\server()
  #13 pmsrc(11): require(string[60] phar:///home/container/PocketMine-MP.phar/src/PocketMine.php)
--- End of exception information ---
[00:37:27.919] [Server thread/EMERGENCY]: An unrecoverable error has occurred and the server has crashed. Creating a crash dump
[00:37:27.932] [Server thread/EMERGENCY]: Please upload the "/home/container/crashdumps/Sun_May_15-00.37.27-UTC_2022.log" file to the Crash Archive and submit the link to the Bug Reporting page. Give as much info as you can.
[00:37:28.632] [Server thread/EMERGENCY]: The crash dump has been automatically

**Comment by supercrafter333** [comment]
Just reset your played times and **update PlayedTime to the latest version**.
