### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by Tuvqlu** [supercrafter333/PlayedTime#9]
Crashes when a player with a space in it joins.

**Comment by supercrafter333** [comment]
Please send me the error.

**Comment by Tuvalu23** [comment]
![DD84B9EC-D064-47BD-BD13-DA109498A334](https://user-images.githubusercontent.com/105463867/172063024-7a219bc6-6aaf-4cbd-9c2a-ec61132b5f22.jpeg)
